jobs:
- job: Complie
  pool:
    name: Hosted Ubuntu 1604

  steps:
    - script: |
        docker build -t xiaomi-r3g-$(Build.BuildNumber) --build-arg GITHUB_TOKEN=$GITHUB_TOKEN .
        docker run -d --name xiaomi-r3g-$(Build.BuildNumber) xiaomi-r3g-$(Build.BuildNumber) cat
        mkdir releases
        docker cp xiaomi-r3g-$(Build.BuildNumber):/home/openwrt/openwrt/bin/targets/ramips/mt7621/* releases/
        docker rm -f xiaomi-r3g-$(Build.BuildNumber)
      displayName: 'Complie'

    - task: GitHubRelease@0
      inputs:
        gitHubConnection: GitHub connection 1
        repositoryName: Indexyz/xiaomi-r3g-openwrt-build
        tagSource: manual
        tag: $(Build.BuildNumber)
        assets: |
          releases/*
      displayName: 'Release'

  timeoutInMinutes: 300
